import { DeconstructedPayout } from '@settlement-agent/shared';

export interface SettlementBatchItem extends DeconstructedPayout {
  clientName: string;
  storeUrl: string;
  status: 'MATH_VERIFIED' | 'STAGED_XERO_DRAFT' | 'ESCALATED_HUMAN_REVIEW' | 'RECONCILED';
  balanceDelta: number;
  syncTarget: 'XERO' | 'QBO';
  escalationReason?: string;
}

export const MOCK_SETTLEMENT_BATCHES: SettlementBatchItem[] = [
  {
    batchId: 'po_1QvExample90214',
    clientName: 'Nordic Atelier',
    storeUrl: 'nordicatelier.com',
    processor: 'STRIPE',
    payoutDate: '2026-09-16T10:00:00Z',
    currency: 'USD',
    grossSales: 10000.00,
    taxCollected: 800.00,
    processingFees: 310.00,
    refunds: 0.00,
    reserveWithheld: 0.00,
    netDeposit: 10490.00,
    confidenceScore: 0.99,
    status: 'MATH_VERIFIED',
    balanceDelta: 0.00,
    syncTarget: 'XERO',
    lines: [
      {
        accountCode: '11500',
        accountName: 'Stripe Payout Clearing Account',
        description: 'Net bank deposit received into clearing account',
        debit: 10490.00,
        credit: 0.00,
      },
      {
        accountCode: '52000',
        accountName: 'Merchant Payment Processing Fees',
        description: 'Stripe interchange and processing fees (2.9% + $0.30)',
        debit: 310.00,
        credit: 0.00,
      },
      {
        accountCode: '40100',
        accountName: 'Gross E-Commerce Sales',
        description: 'Total product gross sales for settlement batch',
        debit: 0.00,
        credit: 10000.00,
      },
      {
        accountCode: '22000',
        accountName: 'Sales Tax Agency Payable',
        description: 'California sales tax collected (CDTFA)',
        debit: 0.00,
        credit: 800.00,
        taxJurisdiction: 'CA-CDTFA',
      },
    ],
  },
  {
    batchId: 'shp_90214812',
    clientName: 'Aura Botanicals',
    storeUrl: 'aurabotanicals.co',
    processor: 'SHOPIFY_PAYMENTS',
    payoutDate: '2026-09-15T14:30:00Z',
    currency: 'USD',
    grossSales: 4250.00,
    taxCollected: 340.00,
    processingFees: 142.20,
    refunds: 85.00,
    reserveWithheld: 0.00,
    netDeposit: 4362.80,
    confidenceScore: 0.98,
    status: 'STAGED_XERO_DRAFT',
    balanceDelta: 0.00,
    syncTarget: 'XERO',
    lines: [
      {
        accountCode: '11510',
        accountName: 'Shopify Payments Clearing',
        description: 'Shopify net payout deposit to operating cash feed',
        debit: 4362.80,
        credit: 0.00,
      },
      {
        accountCode: '52000',
        accountName: 'Merchant Payment Processing Fees',
        description: 'Shopify transaction fee deductions',
        debit: 142.20,
        credit: 0.00,
      },
      {
        accountCode: '49000',
        accountName: 'Sales Returns & Customer Refunds',
        description: 'Customer return for damaged shipment order #1842',
        debit: 85.00,
        credit: 0.00,
      },
      {
        accountCode: '40100',
        accountName: 'Gross E-Commerce Sales',
        description: 'Gross online checkout order revenue',
        debit: 0.00,
        credit: 4250.00,
      },
      {
        accountCode: '22000',
        accountName: 'Sales Tax Agency Payable',
        description: 'New York State Department of Taxation collected',
        debit: 0.00,
        credit: 340.00,
        taxJurisdiction: 'NY-TAX',
      },
    ],
  },
  {
    batchId: 'po_99214710',
    clientName: 'Apex Performance Gear',
    storeUrl: 'apexperformance.io',
    processor: 'STRIPE',
    payoutDate: '2026-09-14T09:15:00Z',
    currency: 'USD',
    grossSales: 18400.00,
    taxCollected: 1288.00,
    processingFees: 542.80,
    refunds: 0.00,
    reserveWithheld: 920.00,
    netDeposit: 18225.20,
    confidenceScore: 0.99,
    status: 'MATH_VERIFIED',
    balanceDelta: 0.00,
    syncTarget: 'QBO',
    lines: [
      {
        accountCode: '11500',
        accountName: 'Stripe Payout Clearing Account',
        description: 'Net cash transfer to checking account',
        debit: 18225.20,
        credit: 0.00,
      },
      {
        accountCode: '11600',
        accountName: 'Merchant Gateway Reserve Receivable',
        description: '5% rolling risk reserve withheld by Stripe underwriting',
        debit: 920.00,
        credit: 0.00,
      },
      {
        accountCode: '52000',
        accountName: 'Merchant Payment Processing Fees',
        description: 'Stripe credit card interchange and merchant fees',
        debit: 542.80,
        credit: 0.00,
      },
      {
        accountCode: '40100',
        accountName: 'Gross E-Commerce Sales',
        description: 'Total equipment product orders',
        debit: 0.00,
        credit: 18400.00,
      },
      {
        accountCode: '22000',
        accountName: 'Sales Tax Agency Payable',
        description: 'Texas Comptroller of Public Accounts sales tax',
        debit: 0.00,
        credit: 1288.00,
        taxJurisdiction: 'TX-COMP',
      },
    ],
  },
  {
    batchId: 'po_dispute_clawback',
    clientName: 'Kinfolk Artisan Goods',
    storeUrl: 'kinfolkgoods.com',
    processor: 'STRIPE',
    payoutDate: '2026-09-13T16:45:00Z',
    currency: 'USD',
    grossSales: 2100.00,
    taxCollected: 168.00,
    processingFees: 74.50,
    refunds: 120.00,
    reserveWithheld: 0.00,
    netDeposit: 2073.50,
    confidenceScore: 0.97,
    status: 'RECONCILED',
    balanceDelta: 0.00,
    syncTarget: 'XERO',
    lines: [
      {
        accountCode: '11500',
        accountName: 'Stripe Payout Clearing Account',
        description: 'Settlement cash deposited',
        debit: 2073.50,
        credit: 0.00,
      },
      {
        accountCode: '52000',
        accountName: 'Merchant Payment Processing Fees',
        description: 'Interchange fees',
        debit: 74.50,
        credit: 0.00,
      },
      {
        accountCode: '49000',
        accountName: 'Sales Returns & Customer Refunds',
        description: 'Order return refund credit',
        debit: 120.00,
        credit: 0.00,
      },
      {
        accountCode: '40100',
        accountName: 'Gross E-Commerce Sales',
        description: 'Product catalog sales',
        debit: 0.00,
        credit: 2100.00,
      },
      {
        accountCode: '22000',
        accountName: 'Sales Tax Agency Payable',
        description: 'State tax payable',
        debit: 0.00,
        credit: 168.00,
      },
    ],
  },
  {
    batchId: 'po_imbalance_review_98',
    clientName: 'Haven Living Spaces',
    storeUrl: 'havenlivingspaces.com',
    processor: 'STRIPE',
    payoutDate: '2026-09-12T11:20:00Z',
    currency: 'USD',
    grossSales: 6500.00,
    taxCollected: 520.00,
    processingFees: 195.00,
    refunds: 0.00,
    reserveWithheld: 0.00,
    netDeposit: 6825.00,
    confidenceScore: 0.91,
    status: 'ESCALATED_HUMAN_REVIEW',
    balanceDelta: 0.02,
    syncTarget: 'XERO',
    escalationReason: 'Rounding discrepancy of $0.02 on California Sales Tax Line after 3 automated retry feedback cycles.',
    lines: [
      {
        accountCode: '11500',
        accountName: 'Stripe Payout Clearing Account',
        description: 'Net cash transfer (Stated: $6,825.00)',
        debit: 6825.02, // 2 cents discrepancy
        credit: 0.00,
      },
      {
        accountCode: '52000',
        accountName: 'Merchant Payment Processing Fees',
        description: 'Processing fees',
        debit: 195.00,
        credit: 0.00,
      },
      {
        accountCode: '40100',
        accountName: 'Gross E-Commerce Sales',
        description: 'Home decor orders',
        debit: 0.00,
        credit: 6500.00,
      },
      {
        accountCode: '22000',
        accountName: 'Sales Tax Agency Payable',
        description: 'Sales tax collected',
        debit: 0.00,
        credit: 520.00,
        taxJurisdiction: 'CA-CDTFA',
      },
    ],
  },
];
